#!/bin/bash

sv start elasticsearch || exit 1
sv start mongodb || exit 1

until curl http://localhost:9200; do echo "waiting for ElasticSearch to come online..."; sleep 3; done
curl -X GET 'http://localhost:9200/_cluster/health?wait_for_status=green&timeout=10s'

source /etc/envvars
env

cd /graylog/bin
exec 2>&1
exec ./graylogctl run
